version: 2

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - main: ./cmd/speedflare/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - openbsd
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - s390x
      - ppc64
      - ppc64le
      - riscv64
      - mips
      - mips64
      - mipsle
      - mips64le
      - loong64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ["binary"]
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- $cleanArch := .Arch | replace "_v1" "" | replace "_v8.0" "" | replace "_sse2" "" | replace "_6" "" | replace "_power8" "" | replace "_rva20u64" "" | replace "_hardfloat" "" }}
      {{- if eq $cleanArch "amd64" }}amd64
      {{- else if eq $cleanArch "386" }}i386
      {{- else if eq $cleanArch "arm" }}arm
      {{- else if eq $cleanArch "arm64" }}arm64
      {{- else if eq $cleanArch "ppc64le" }}ppc64le
      {{- else if eq $cleanArch "ppc64" }}ppc64
      {{- else if eq $cleanArch "riscv64" }}riscv64
      {{- else if eq $cleanArch "mips64le" }}mips64le
      {{- else if eq $cleanArch "mips64" }}mips64
      {{- else if eq $cleanArch "mipsle" }}mipsle
      {{- else if eq $cleanArch "mips" }}mips
      {{- else if eq $cleanArch "loong64" }}loong64
      {{- else }}{{ $cleanArch }}{{ end -}}
      {{- if eq .Os "windows" }}.exe{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
