version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/speedflare/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch: [386, "arm", "amd64", "arm64"]
    goamd64:
      - v3
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.version={{.Version}}

upx:
  - enabled: true
    compress: 6
    lzma: true

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
