version: 2

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - main: ./cmd/speedflare/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - openbsd
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - s390x
      - ppc64
      - ppc64le
      - riscv64
      - mips
      - mips64
      - mipsle
      - mips64le
      - loong64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ["binary"]
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- $arch := .Arch -}}
      {{- $arch = replace $arch "_v1" "" -}}
      {{- $arch = replace $arch "_v8.0" "" -}}
      {{- $arch = replace $arch "_sse2" "" -}}
      {{- $arch = replace $arch "_6" "" -}}
      {{- $arch = replace $arch "_power8" "" -}}
      {{- $arch = replace $arch "_rva20u64" "" -}}
      {{- $arch = replace $arch "_hardfloat" "" -}}
      {{- switch $arch }}
        {{- case "amd64" }}amd64
        {{- case "386" }}i386
        {{- case "arm" }}arm
        {{- case "arm64" }}arm64
        {{- case "ppc64le" }}ppc64le
        {{- case "ppc64" }}ppc64
        {{- case "riscv64" }}riscv64
        {{- case "mips64le" }}mips64le
        {{- case "mips64" }}mips64
        {{- case "mipsle" }}mipsle
        {{- case "mips" }}mips
        {{- case "loong64" }}loong64
        {{- else }}{{ $arch }}
      {{- end -}}
      {{- if eq .Os "windows" }}.exe{{- end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
