version: 2

hooks:
  - go mod download
  - go generate ./...

builds:
  - main: ./cmd/speedflare/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - openbsd
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - s390x
      - ppc64
      - ppc64le
      - riscv64
      - mips
      - mips64
      - mipsle
      - mips64le
      - loong64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: ["binary"]
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}arm
      {{- else }}{{ .Arch }}{{ end -}}
      {{- if eq .Os "windows" }}.exe{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"